### ISSUE TITLE
support for FATEK proto over serial connection RS232/485

### ISSUE THREAD

**Issue by klawczys** [s4u/jfatek#1]
Hi!

It's stated that it's fairly easy to add support for additional transport methods. It would be nice if the jfatek have support for FATEK proto over serial connection. 

Unfortunately, I'm not Java dev and could not help in implementation. I could help in testing. I'm building home automation based on openhab and Fatek PLC. Just want to use serial since it's much cheaper option. 

Thanks for nice work!

**Comment by slawekjaranowski** [comment]
I prepared PR for openhab which add support for serial port support in openhab
https://github.com/openhab/openhab1-addons/pull/5877

You can test it early, instruction how to test is on openhab formu: https://community.openhab.org/t/fatek-binding-to-use-usb-cabel/74509
