### ISSUE TITLE
PLC Connection

### ISSUE THREAD

**Issue by DamianOczkowski** [s4u/jfatek#2]
Hello. 
I just started using this lib, and I try integrate JHipster and PLC device using this. I would like to ask if it's any possibility to connect with PLC device all the time?  I saw in documentation that in connection params we cantype timeout connection param (deafult 5000). It means that every time when I send request from server, I must create new instance of connection and after recive data close the connection? 
eg.: 
		
```
try {
      fatekPLC = new FatekPLC(connectionParam);
      List<RegValue> list = new FatekReadDataCmd(fatekPLC, temperatureReg, 12).send();
      fatekPLC.close();
} catch (Exception e) {
	System.out.println("error during connection");
}
```

**Comment by slawekjaranowski** [comment]
You can create connection once and use it many times, as standard socket connection.

I did't test FatekPLC connection in multithread environment so you should synchronize access to share connecton socket.

Of course your application should be ready to recreate connection if some error occurs.

Example shows usage in simple case.

**Comment by DamianOczkowski** [comment]
OK, so how can I check if connection is active ? I don't see any methods in FatekPLC class.

**Comment by slawekjaranowski** [comment]
Ok. I checked again.

You needn't check connection status.

Once you create FatekPLC object connection is managed in this object. When some IOException occurs internal connection is closed and new connection is established when you call next send method.
If everything is ok - old connection is reused.
