### ISSUE TITLE
How to read counters and timers

### ISSUE THREAD

**Issue by lazyweirdo** [s4u/jfatek#4]
Hello, great job, i have it working but i think i am not understanding something.
I have the following ladder program

![screen](https://user-images.githubusercontent.com/15219561/71544906-dd184a80-2984-11ea-82d9-1e18ee20201e.jpg)

I thought it was possible to read C0 and T200 using something like:

`List<Boolean> values = new FatekReadDataCmd(fatekPLC, DataReg.C(0), 1).send();`

Forget the Boolean ... actually the question is how to properly read C0 and T200 

Again, it is a great job ... and it is almost the only one i managed to get working.

I tried also with modbus, but i am not able to read data other than coils with it

Cheers

**Comment by lazyweirdo** [comment]
I figured it out.
It is done lke this:

`List<RegValue> values = new FatekReadDataCmd(fatekPLC, DataReg.RT(200), 1).send();`

Paste, just in case somebody finds it helpful
cheers

**Comment by slawekjaranowski** [comment]
You are right, `Cxxxx` and `Txxxx` register return status of discrete in this case for counter or timer.

But register `RCxxxx`, `RTxxxx` return 16 bit current value of counter and timer, and `DRCxxxx`, `DRTxxxx` return 32 bit value.

**Comment by AsnanRajput** [comment]
Hello, you have done an amazing job, I'm very glad..... but I'm beginner in java programming and don't know how to utilize this library..... Can you make a guideline video how to use this library and what initial libraries we need to add.
Again bundle of thanks

**Comment by slawekjaranowski** [comment]
@AsnanRajput  - Can you give more details, what is your case, what do you want to achieve an how do you want use our library? What did you do to this time?
